### ISSUE TITLE
Criar meta calorias diárias

### ISSUE THREAD

**Issue by JoaoVictor-FA** [JhonPrFer/CalorieCheck#4]

**Comment by milenaelen** [comment]
### Descrição
Como usuário, eu quero criar uma meta de calorias diárias para que eu possa trabalhar para alcançá-las
O usuário deve poder definir uma meta de calorias diárias, que será exibida na página principal do aplicativo. Caso a meta ainda não tenha sido definida, um botão deve ser exibido, permitindo ao usuário criar uma nova meta. 

O usuário só poderá cadastrar uma meta por vez, e essa meta poderá ser removida conforme necessário.

### Crítérios de Aceitação 

- [ ] A meta de calorias diárias deve ser exibida na página principal do aplicativo.
- [ ] Se não houver a meta na página principal, deve haver um botão com a label para poder criar essa meta.
- [ ] Uma vez cadastrada, a meta deve ser exibida no lugar do botão, mostrando o valor definido pelo usuário.
